import { useEffect } from 'react';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import { Row } from "antd";
import { useDispatch, useSelector } from "react-redux";

import { setList } from "@/store/reducers/ticket";

import { api } from '@/services/api';

import { Header } from '@/components/Header';
import { CityAndDateFilter } from '@/components/CityAndDateFilter';
import { TicketList } from '@/components/TicketList';
import { KnowMorePackages } from '@/components/KnowMorePackages';
import { BrazilCities } from '@/components/BrazilCities';
import { Footer } from '@/components/Footer';

import styles from '../styles/Home.module.scss';
import { PriceFilter } from '@/components/PriceFilter';

interface HomeProps {
  list: any[];
}

const Home: NextPage<HomeProps> = ({ list }: HomeProps) => {
  const dispatch = useDispatch();
  const ticketList: Array<any> = useSelector((state: any) => state.ticket.list)

  useEffect(() => {
    if(ticketList.length === 0){
      dispatch(setList(list))
    }
  }, [dispatch, list, ticketList.length])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CityAndDateFilter/>
        <Row justify="space-between" className={styles.filterAndListContainer}>
          <PriceFilter/>
          <TicketList/>
        </Row>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const ticketList = await api.get("/ticket");
  return {
    props: {
      list: ticketList.data
    }
  }
}

export default Home
